apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: eksworkshop-eksctl
    region: $AWS_REGION
nodeGroups:
    - name: ng-test-jenkins-spot
      minSize: 0
      maxSize: 5
      desiredCapacity: 1
      instancesDistribution:
        instanceTypes: ["m5.large", "m5d.large", "m4.large","t3.large","t3a.large","m5a.large","t2.large"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: capacity-optimized
      labels:
        lifecycle: Ec2Spot
        intent: jenkins-agents
        aws.amazon.com/spot: "true"
      tags:
          k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
          k8s.io/cluster-autoscaler/node-template/label/intent: jenkins-agents
          k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
      iam:
        withAddonPolicies:
          autoScaler: true